#普通数据的配置
name: zhangsan

#对象的配置
person:
  name: zhangsan
  age: 22
  addr: beijing


server:
  port: 8082

#行内配置
person1: {name: lisi,age: 12,addr: beihaidao}

#配置数据.集合(普通字符串)
city:
  - beijing
  - sahgnhai
  - tianjing

#行内表达
city1: [beijing,tianjing,shagnhai]

#配置数据.集合(对象数据)
student:
  - name: tom
    age: 11
    addr: beijing
  - name: lucy
    age: 55
    addr: tianjing
#行内表达
students: [{name: tom,age: 11,addr: jiangxi},{name: lucy,age: 15,addr: nanjing}]


#map配置
map:
  key1: value1
  key2: value2






